// WARNING: Do not edit this file. Copy or rename it as connection.js before change it

const PROTOCOL = 'https'; // http or https
const HOST = 'fhcomplete.org'; // host name
const PROJECT = 'ClientAddonTemplate'; // project name
const PATH = 'controller'; // path to the router
const ROUTER = 'router.php'; // router name
