<?php

// WARNING: Do not edit this file. Copy or rename it as config.php before change it

$activeConnection = 'DEFAULT'; // the used configuration set of the chosen connection

// Example of a configuration set, all parameters are required!
$connection = array(
	'DEFAULT' => array(
		USERNAME => 'fhcomplete', //
		PASSWORD => '****', //
		API_KEY_NAME => 'FHC-API-KEY', //
		API_KEY_VALUE => 'testapikey@fhcomplete.org', //
		PROTOCOL => 'https', //
	    HOST => 'fhcomplete.org', //
	    PATH => 'fhcomplete', //
	    ROUTER => 'index.ci.php', //
	    WS_PATH => 'api/v1' //
	)
);

// Example of route configuration
// Every element of the first level is the alias of the remote web service
// Every first element must contain a string with the <path/name/method to call> of the remote web service (REQUIRED)
// OR an array having:
//	- as element REMOTE_WS the <path/name/method to call> of the remote web service (REQUIRED)
//	- as element HOOK the hook to manipulate the response from the remote web service (OPTIONAL)
//	- as element LOGIN_REQUIRED a boolean: if true (default) to perform this call the user must be logged in (OPTIONAL)
//
// To use login capabilities must be present the element LOCAL_LOGIN_CALL in the first level, and in the array
// of it must be present the element USERNAME
$route = array(
	LOCAL_LOGIN_CALL => array(
		REMOTE_WS => 'CheckUserAuth/CheckByUsernamePassword',
		HOOK => 'hookLogin',
		USERNAME => 'username'
	),
    'testHook'  => array(	//
        REMOTE_WS => 'Test/Test', //
        HOOK => 'hookTest', //
		AUTH => false	//
    ),
	'testNoHook'  => 'Test/Test'
);
